### ISSUE TITLE
Google colab での pip install タイムアウト

### ISSUE THREAD

**Issue by devemin** [Kazuhito00/Tensorflow2-ObjectDetectionAPI-Colab-Hands-On#2]
こんばんは！

こちらのリポジトリを試させて頂いてるのですが、
Google Colab の作業の途中の、

!cp /content/models/research/object_detection/packages/tf2/setup.py .
!python -m pip install . 

の所がどうしてもタイムアウトになり、続く作業が出来なかったので、調べてみたら、
pip のバージョンが上がってると依存チェックが時間がかかるようで、

!python -m pip install . --use-deprecated=legacy-resolver
というふうにオプションをつけると、うまく数分で終わりました。

参考：
https://qiita.com/ksato9700/items/ec30d726a1508c7985a0
https://note.com/npaka/n/n92580a746f2d

素晴らしいリポジトリをありがとうございます。
ご報告まで m(_ _)m

**Comment by Kazuhito00** [comment]
ご連絡ありがとうございます。
「!python -m pip install . --use-deprecated=legacy-resolver」に変更しました。
tensorflow/modelsリポジトリ側でも問題になっているようなので、ウォッチして対応され次第、取り込もうかと思います。
* [pip is looking for multiple version of <library> to determine which version is compatible with other requirements. #10375](https://github.com/tensorflow/models/issues/10375)

---

For those who searched in English.

The following pip installation takes a long time to resolve dependencies and times out.
Therefore, the "--use-deprecated = legacy-resolver" option is specified as a provisional support.

```
!cp /content/models/research/object_detection/packages/tf2/setup.py .
!python -m pip install .
```

This problem is also an issue on the tensorflow/models repository side.
It will be reflected in this repository as soon as it is supported.
* [pip is looking for multiple version of <library> to determine which version is compatible with other requirements. #10375](https://github.com/tensorflow/models/issues/10375)
